### ISSUE TITLE
Cannot see the project website

### ISSUE THREAD

**Issue by Seasawher** [victorstanciu/dbv#106]
I tried to view the project site according to the README, but I was sent to another site.

![screenshot01](https://user-images.githubusercontent.com/47292598/193036941-6c5cb1e7-8506-49ea-ad7d-5b25adc42505.jpg)

**Comment by davidsneighbour** [comment]
That's what happens when a project is abandoned for many years. Did you check the times of the last changes? The nearest last change is 5 years old. I suggest you look for other and more current ways to keep your database up to date. 

I switched over to [Phinx](https://phinx.org/) a while back and can only suggest looking into it.

**Comment by Seasawher** [comment]
Thanks
