### ISSUE TITLE
What happens when two people are create folders with the same revision number

### ISSUE THREAD

**Issue by patforg** [victorstanciu/dbv#80]
I'm trying to decide if this is a good solution to use at the company I work for, so far it looks like a good solution, it's a tough problem to tackle.

What happens when two people are create folders with the same revision number?

Maybe add more examples on the flow.

**Comment by hectore-imh** [comment]
Bumping this issue up again because I'm having the same dilemma as well. While the solution above me looks interesting, it still does not solve the problem of having two people working on the database at the same time run into an issue of possible creating two folders of the same name.
i.e. (Two guys see 20141218001 already created, and both of them end up creating 20141218002.)

Wondering as well how any of the others guys here who've implemented DBV into their work environments have handled this situation.

**Comment by victorstanciu** [comment]
I have only used DBV in small teams, so I didn't bump into this problem myself. I am open to any suggestions.

**Comment by sascoms** [comment]
We use date and time as revision numbers. Like 201506251432

**Comment by victorstanciu** [comment]
Yeah, I guess if you really want to make sure each developer's folder names are unique, you could ask them to append some sort of unique id to their revision directories, like "patforg", "victorstanciu", etc.
