### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tobiasmuecksch** [victorstanciu/dbv#87]
I wonder if this project is abandoned since the last release is from December 2012.

Is there any well maintained fork?

**Comment by victorstanciu** [comment]
Hi Tobias,

It's, but I admit I haven't developed any new features for it for a very long time. It's not just that I've been busy (which I have), but I also haven't been using dbv myself for quite some time now, because I've switched to using MySQL Workbench, which can automatically sync visual database diagrams with actual databases, and can even sync two remote databases.

I promise I will dedicate more time to the project in the following weeks, and perhaps bring it to a stage where I can start using it myself again.

Have a nice day!
